#!/usr/bin/env bash
# Run 2026-08-07-sr1-noctx-musique, generated by exp.py from configs/sr1_musique_noctx.yaml.
# Written before any stage starts, so the run stays reproducible even if
# the process is killed.
set -euo pipefail
cd /path/to/repo

HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 \
  /path/to/venv/bin/python build_eval_variants.py --context none --input /path/to/repo/runs/2026-08-07-sr1-best-musique/retrieval.jsonl --output /path/to/repo/runs/2026-08-07-sr1-noctx-musique/retrieval.jsonl

# judge: 32 shards of answer_judge_llms.py, then merged
# /path/to/venv/bin/python /path/to/Q-RAG-feedback/answer_judge_llms.py --retriever-logfile <shard>.jsonl --output-file <shard>.json --base-url http://127.0.0.1:8010/v1 --answer-model Qwen3-4B --max-samples 100000 --max-tokens 1000 --judge-max-tokens 100

python exp.py run --config configs/sr1_musique_noctx.yaml --only score
