#!/usr/bin/env bash
# Run 2026-08-02-gte-pool-diag-k1000, generated by exp.py from configs/gte_pool_diag_k1000.yaml.
# Written before any stage starts, so the run stays reproducible even if
# the process is killed.
set -euo pipefail
cd /path/to/repo

CUDA_VISIBLE_DEVICES=6 HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 \
  /path/to/venv/bin/python fullwiki_qrag.py retrieve --index-dir /path/to/data/full-wiki/wiki18-qrag-jul21-best-raw --qrag-repo /path/to/Q-RAG-feedback --device cuda:0 --model-dtype float32 --state-source critic --input /path/to/data/hotpotqa/hotpot_dev_fullwiki_v1.json --output /path/to/repo/runs/2026-08-02-gte-pool-diag-k1000/retrieval.jsonl --batch-size 64 --top-k 1000 --steps 1 --mode fixed --reranker none --log-candidates full --candidate-index-dir /path/to/data/full-wiki/wiki18-gte --candidate-backend torch-cuda --dedupe-titles --trust-remote-code --no-auto-prepare

# judge: 32 shards of answer_judge_llms.py, then merged
# /path/to/venv/bin/python /path/to/Q-RAG-feedback/answer_judge_llms.py --retriever-logfile <shard>.jsonl --output-file <shard>.json --base-url http://127.0.0.1:8010/v1 --answer-model Qwen3-4B --max-samples 100000 --max-tokens 1000 --judge-max-tokens 100

python exp.py run --config configs/gte_pool_diag_k1000.yaml --only score
