#!/usr/bin/env bash
# Run 2026-08-08-search-zeroshot-hotpotqa-noquota, generated by exp.py from configs/search_zeroshot_hotpotqa_noquota.yaml.
# Written before any stage starts, so the run stays reproducible even if
# the process is killed.
set -euo pipefail
cd /path/to/repo

CUDA_VISIBLE_DEVICES=1 HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 \
  /path/to/venv/bin/python fullwiki_qrag.py search --index-dir /path/to/data/full-wiki/wiki18-gte --qrag-repo /path/to/repo/Q-RAG_for_full-wiki --device cuda:0 --model-dtype float32 --input /path/to/data/hotpotqa/hotpot_dev_fullwiki_v1.json --output /path/to/repo/runs/2026-08-08-search-zeroshot-hotpotqa-noquota/retrieval.jsonl --batch-size 64 --top-k 100 --steps 6 --max-chunks-per-title 6 --log-candidates none --no-auto-prepare

# judge: 32 shards of answer_judge_llms.py, then merged
# /path/to/venv/bin/python /path/to/Q-RAG-feedback/answer_judge_llms.py --retriever-logfile <shard>.jsonl --output-file <shard>.json --base-url http://127.0.0.1:8010/v1 --answer-model Qwen3-4B --max-samples 100000 --max-tokens 1000 --judge-max-tokens 100

python exp.py run --config configs/search_zeroshot_hotpotqa_noquota.yaml --only score
