#!/usr/bin/env bash
# Run 2026-08-10-sr1-rawmix4b-last-nq, generated by exp.py from configs/sr1_rawmix4b-last_nq.yaml.
# Written before any stage starts, so the run stays reproducible even if
# the process is killed.
set -euo pipefail
cd /path/to/repo

CUDA_VISIBLE_DEVICES=0 HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 \
  /path/to/venv/bin/python fullwiki_qrag.py search --index-dir /path/to/data/full-wiki/wiki18-gte --qrag-repo /path/to/repo/Q-RAG_for_full-wiki --device cuda:0 --model-dtype float32 --input /path/to/repo/runs/shared/searchr1/nq.jsonl --output /path/to/repo/runs/2026-08-10-sr1-rawmix4b-last-nq/retrieval.jsonl --batch-size 64 --top-k 100 --steps 6 --max-chunks-per-title 2 --log-candidates none --checkpoint /path/to/repo/Q-RAG_for_full-wiki/runs/Aug08_20-39-33_rawmix4b/model_last.pt --state-source critic --no-auto-prepare

# judge: 32 shards of answer_judge_llms.py, then merged
# /path/to/venv/bin/python /path/to/repo/answer_judge.py --retriever-logfile <shard>.jsonl --output-file <shard>.json --base-url http://127.0.0.1:8010/v1 --answer-model Qwen3-4B --max-samples 100000 --max-tokens 1000 --judge-max-tokens 100 --contract v2 --dataset sr1_nq

python exp.py run --config configs/sr1_rawmix4b-last_nq.yaml --only score
