#!/usr/bin/env bash
# Run 2026-08-02-gte-only-n2-steps4, generated by exp.py from configs/gte_only_n2_steps4.yaml.
# Written before any stage starts, so the run stays reproducible even if
# the process is killed.
set -euo pipefail
cd /path/to/repo

HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 \
  /path/to/venv/bin/python build_eval_variants.py --context truncate --input /path/to/repo/runs/2026-08-02-gte-only-n2-steps6/retrieval.jsonl --output /path/to/repo/runs/2026-08-02-gte-only-n2-steps4/retrieval.jsonl --steps 4

# judge: 32 shards of answer_judge_llms.py, then merged
# /path/to/venv/bin/python /path/to/Q-RAG-feedback/answer_judge_llms.py --retriever-logfile <shard>.jsonl --output-file <shard>.json --base-url http://127.0.0.1:8010/v1 --answer-model Qwen3-4B --max-samples 100000 --max-tokens 1000 --judge-max-tokens 100

python exp.py run --config configs/gte_only_n2_steps4.yaml --only score
