type: llm  # llm, occ

feedback_dict:
  llm: ${feedback.llm_answer}
  occ: ${feedback.occ_status}

llm_answer:
  _target_: rl.feedback.LlmAnswer
  model: Qwen3-4B
  base_url: http://localhost:9100/v1
  api_key: ''
  max_tokens: 1000
  thinking: false
  task: ${envs.task}
  reward_type: exact-match  # exact-match or llm-judge

occ_status:
  _target_: rl.feedback.OccStatus
  llm_path: "../Qwen/OCC-RAG-1.7B"
  gpu_util: 0.5
  max_tokens: 2000
