#!/usr/bin/env bash
# Run 2026-08-02-pool-oracle-chunks-n2-k6, generated by exp.py from configs/pool_oracle_chunks_n2_k6.yaml.
# Written before any stage starts, so the run stays reproducible even if
# the process is killed.
set -euo pipefail
cd /path/to/repo

HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 \
  /path/to/venv/bin/python candidate_pool.py select --input /path/to/repo/runs/2026-08-02-gte-pool-diag/retrieval.jsonl --index-dir /path/to/data/full-wiki/wiki18-qrag-jul21-best-raw --steps 6 --output /path/to/repo/runs/2026-08-02-pool-oracle-chunks-n2-k6/retrieval.jsonl --prefer gold-sentence --gold-source /path/to/data/hotpotqa/hotpot_dev_distractor_v1.json --max-per-title 2

# judge: 32 shards of answer_judge_llms.py, then merged
# /path/to/venv/bin/python /path/to/Q-RAG-feedback/answer_judge_llms.py --retriever-logfile <shard>.jsonl --output-file <shard>.json --base-url http://127.0.0.1:8010/v1 --answer-model Qwen3-4B --max-samples 100000 --max-tokens 1000 --judge-max-tokens 100

python exp.py run --config configs/pool_oracle_chunks_n2_k6.yaml --only score
